---
title: "Protocolo de Prevención e Intervención frente al Acoso Sexual y por razón de sexo: Guías para Direcciones, Víctimas-testigos y Responsables de campaña"
date: 2025-07-31
output:
  distill::distill_article:
    self_contained: false
---
<div style="text-align: justify;">
Se difunden guías de actuación específicas sobre el Protocolo de Acoso Sexual/por razón de sexo para las direcciones de los centros, para acompañamiento de las víctimas y para las personas responsables de las campañas oceanográficas.
</div>

https://saco.csic.es/s/eHmkpiq52AGRMQ2

<div style="text-align: justify;">
Se han generado críticas a estas guías por no ser claras en cómo actuar.  
Mencionan autoridad en tierra y direcciones de correo genérico sin saber quién está detrás o sabiéndose que la formación que tienen esas personas es insuficiente.
Tiene que haber personas que puedan responder, con formación y que vayan a tomar decisiones concretas. Esto es crucial, porque la dinámica habitual es que no se crea a las víctimas, que se las culpabilice, que se las desembarque a ellas y no a los acosadores o agresores, que se las revictimice institucionalmente, etc. Todo ello derivado de la falta de formación y, demasiado habitualmente, de los sesgos machistas de las personas responsables de tomar decisiones.
También se usa conceptos como comportamientos inadecuados. Esto es un eufemismo. El acoso sexual y el acoso por razón de género no puede ser tratado como comportamientos inadecuados, y quienes toman decisiones deben aprender a diferenciar lo que es una falta, un delito penal y una infracción laboral de lo que es un simple comportamiento inadecuado. El acoso  sexual y el acoso por razón de género se definen como cualquier comportamiento, verbal o físico,  que tenga el propósito, o produzca el efecto, de crear un entorno degradante, intimidatorio u ofensivo. 
</div>